import { Check, CircleHelp, KeyRound, LockKeyhole, RefreshCw, ServerCog, ShieldCheck, SlidersHorizontal } from 'lucide-react';
import { useEffect, useState } from 'react';
import { AppShell, MobileNav } from '@/components/app-shell';
import { Button } from '@/components/ui/button';

const settingsKey = 'caseflow-preferences';

export default function Settings() {
  const [autoSummary, setAutoSummary] = useState(true);
  const [retainSources, setRetainSources] = useState(true);
  const [saved, setSaved] = useState(false);
  useEffect(() => {
    const raw = localStorage.getItem(settingsKey);
    if (raw) {
      try { const parsed = JSON.parse(raw) as { autoSummary?: boolean; retainSources?: boolean }; setAutoSummary(parsed.autoSummary ?? true); setRetainSources(parsed.retainSources ?? true); } catch { /* use defaults */ }
    }
  }, []);
  const save = () => { localStorage.setItem(settingsKey, JSON.stringify({ autoSummary, retainSources })); setSaved(true); window.setTimeout(() => setSaved(false), 1800); };
  return <AppShell><MobileNav />
    <div className="caseflow-rise"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-primary">Workspace controls</p><h1 className="mt-2 font-serif text-[42px] leading-none tracking-[-.045em]">Settings</h1><p className="mt-3 max-w-[500px] text-[13px] leading-relaxed text-muted-foreground">Keep processing preferences close to the way your team reviews work.</p></div>
    <div className="mt-8 grid max-w-[1040px] gap-5 lg:grid-cols-[1.2fr_.8fr]">
      <div className="space-y-5">
        <section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary/10 text-primary"><SlidersHorizontal className="h-4 w-4" /></div><div><h2 className="text-[15px] font-bold">Processing preferences</h2><p className="mt-0.5 text-[11px] text-muted-foreground">Defaults for every new complaint document.</p></div></div><div className="mt-6 divide-y divide-border">{[{ label: 'Generate internal case summary', description: 'Give reviewers a concise operational handoff.', value: autoSummary, set: setAutoSummary, test: 'toggle-auto-summary' }, { label: 'Retain source preview', description: 'Keep the source excerpt alongside extracted fields.', value: retainSources, set: setRetainSources, test: 'toggle-retain-sources' }].map((setting) => <div key={setting.label} className="flex items-center justify-between gap-5 py-4 first:pt-0 last:pb-0"><div><p className="text-[12px] font-bold">{setting.label}</p><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">{setting.description}</p></div><button type="button" role="switch" aria-checked={setting.value} data-testid={setting.test} onClick={() => setting.set(!setting.value)} className={`relative h-6 w-11 shrink-0 rounded-full transition-colors ${setting.value ? 'bg-primary' : 'bg-muted-foreground/30'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-card shadow-sm transition-transform ${setting.value ? 'translate-x-6' : 'translate-x-1'}`} /></button></div>)}</div><div className="mt-6 flex justify-end"><Button type="button" data-testid="button-save-settings" onClick={save} className="h-9 gap-2 bg-primary px-4 text-[11px] font-bold text-primary-foreground hover:bg-primary/90">{saved ? <Check className="h-3.5 w-3.5" /> : null}{saved ? 'Saved' : 'Save preferences'}</Button></div></section>
        <section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-muted text-foreground"><KeyRound className="h-4 w-4" /></div><div><h2 className="text-[15px] font-bold">API readiness</h2><p className="mt-0.5 text-[11px] text-muted-foreground">Connection details for your processing workspace.</p></div></div><div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex items-center gap-2 text-[12px] font-bold text-emerald-800"><span className="h-2 w-2 rounded-full bg-emerald-500" />Connected and ready</div><p className="mt-2 text-[11px] leading-relaxed text-emerald-800/70">Case processing endpoints are responding normally. Documents are sent securely for structured extraction.</p><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-white/70 px-2.5 py-1 font-mono text-[9px] uppercase tracking-wider text-emerald-800">Extraction online</span><span className="rounded-full bg-white/70 px-2.5 py-1 font-mono text-[9px] uppercase tracking-wider text-emerald-800">Drafting online</span></div></div><div className="mt-4 flex items-center justify-between border-t border-border pt-4"><span className="flex items-center gap-2 text-[11px] text-muted-foreground"><RefreshCw className="h-3.5 w-3.5" />Last checked just now</span><button type="button" data-testid="button-check-api" onClick={() => window.location.reload()} className="text-[11px] font-bold text-primary hover:underline">Check again</button></div></section>
      </div>
      <div className="space-y-5"><section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-primary" /><h2 className="text-[13px] font-bold">Data handling</h2></div><ul className="mt-4 space-y-4">{[['Encrypted in transit', 'Documents use secure transport while processing.'], ['Team-scoped workspace', 'Only your support workspace can access these cases.'], ['Review before sending', 'Drafts are prepared for a human review, never sent automatically.']].map(([title, copy]) => <li key={title} className="flex gap-3"><Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-emerald-600" /><div><p className="text-[11px] font-bold">{title}</p><p className="mt-1 text-[10px] leading-relaxed text-muted-foreground">{copy}</p></div></li>)}</ul></section><section className="rounded-2xl border border-border bg-muted/55 p-5 sm:p-6"><div className="flex items-center gap-2"><CircleHelp className="h-4 w-4 text-primary" /><h2 className="text-[13px] font-bold">Need a hand?</h2></div><p className="mt-3 text-[11px] leading-relaxed text-muted-foreground">Your workspace is configured for text, PDF, and Word complaint documents. If a document fails processing, try a smaller file or contact your workspace administrator.</p><div className="mt-4 flex items-center gap-2 text-[10px] font-bold text-primary"><ServerCog className="h-3.5 w-3.5" />Processing status: nominal</div></section></div>
    </div>
  </AppShell>;
}
